### ISSUE TITLE
Add catching of `record=True`

### ISSUE THREAD

**Issue by kornicameister** [kornicameister/loguru-mypy#18]
Ref: #6 
Ref: https://github.com/python/mypy/issues/9010

This is basically an extension of what was implemented for #6. With `record=True` user can access special dictionary inside of a template. `record=False` basically means opposite so user should be told that he is doing the wrong thing for both of cases;

```python
logger.info('{record["msg"]}') # bad
logger.opt(record=True).info('{record["msg"]}') # ok
```

**Comment by kornicameister** [comment]
@Delgan  is following possible

```python
logger.opt(record=True).info('record={record}', record=lambda : {})
```
?

**Comment by Delgan** [comment]
@Delgan Nope, it raises an error.

```python
>>> from loguru import logger
>>> logger.opt(record=True).info('record={record}', record=lambda : {})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "loguru/_logger.py", line 1971, in info
    __self._log("INFO", None, False, __self._options, __message, args, kwargs)
  File "loguru/_logger.py", line 1934, in _log
    raise TypeError(
TypeError: The message can't be formatted: 'record' shall not be used as a keyword argument while logger has been configured with '.opt(record=True)'
```

**Comment by kornicameister** [comment]
Alright, so we have another thingy to check ;-)
